### ISSUE TITLE
climate arrays

### ISSUE THREAD

**Issue by andyrich** [andyrich/SVIGFM_model#10]
update climates arrays

**Comment by ckikuchi** [comment]
Changes made:
1. Added new subfolder "prcp" with updated precipitation arrays extended into subcatchments. Renamed from "finf" to "prcp". 
2. Replaced reference ET (called PET) files from extended model domain, BCM v8
3. Replaced "pet_driver" and "precip_driver" with updates to file names and pathing
4. Replaced "farms_driver" with a version including updated WBS: (a) "farm2014.dat" beginning Jan-2014 {SP#530}, and (b) "farm2016.dat" beginning Jan-2016 {SP#554}

**Comment by andyrich** [comment]
I don't see any commits here.
